import os
from time import sleep

def clear():
	os.system('cls' if os.name in ('nt', 'dos') else 'clear')
clear()
print('|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|')
print('|          ccOS           |')
print('|        Loading.         |')
print('|_________________________|')
sleep(0.3)
clear()
print('|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|')
print('|          ccOS           |')
print('|        Loading..        |')
print('|_________________________|')
sleep(0.3)
clear()
print('|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|')
print('|          ccOS           |')
print('|        Loading...       |')
print('|_________________________|')
sleep(0.3)
clear()
print('|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|')
print('|          ccOS           |')
print('|        Loading.         |')
print('|_________________________|')
sleep(0.3)
clear()
print('|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|')
print('|          ccOS           |')
print('|        Loading..        |')
print('|_________________________|')
sleep(0.3)
clear()
print('|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|')
print('|          ccOS           |')
print('|        Loading...       |')
print('|_________________________|')
sleep(0.3)
clear()
print('|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|')
print('|          ccOS           |')
print('|        Loading.         |')
print('|_________________________|')
sleep(0.3)
clear()
print('|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|')
print('|          ccOS           |')
print('|        Loading..        |')
print('|_________________________|')
sleep(0.3)
clear()
print('|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|')
print('|          ccOS           |')
print('|        Loading...       |')
print('|_________________________|')
sleep(0.3)
os.system("python3 C:/ccOS/32lib/sys/cclogin.py")